site:
  title: Writing Test
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://magnolia-writing-test.netlify.app/
  start_page: writing-test::index.adoc
content:
  sources:
  - url: https://git.magnolia-cms.com/scm/documentation/writing-test.git
    branches: master
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
